name: Fetch current age criteria

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Cache gems
      uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-rubocop-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-rubocop-
    - name: Install gems
      run: |
        bundle install --jobs 4 --retry 3
    - name: Get current age criteria
      id: criteria
      run: echo ::set-output name=age::$(bundle exec ruby script/get_current_age_criteria.rb)
    - name: test echo var (to be replaced with tweeting)
      run: echo ${{ steps.criteria.outputs.age }}
