name: Tweet current age criteria

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install gems
      run: |
        bundle install --jobs 4 --retry 3
    - name: Get current age criteria
      id: criteria
      run: echo ::set-output name=age::$(bundle exec ruby script/get_current_age_criteria.rb)
    - name: Output age criteria
      run: echo ${{ steps.criteria.outputs.age }}
    - name: Should i text it?
      id: should-i-send
      run: |
        if [[ '${{ steps.criteria.outputs.age }}' =~ ${{ secrets.SMS_REGEX }} ]]; then
            echo ::set-output name=match::true
        fi
    - name: 'Send SMS Notification'
      if: steps.should-i-send.outputs.match == 'true'
      uses: twilio-labs/actions-sms@v1
      with:
        fromPhoneNumber: '+447782588983'
        toPhoneNumber: ${{ secrets.TO_PHONE_NUMBER }}
        message: 'Jab booking criteria changed: ${{ steps.criteria.outputs.age }}'
      env:
        TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
        TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
        TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
    - name: Tweet current age criteria
      uses: devigned/go-twitter-action@v1
      with:
        message: ${{ steps.criteria.outputs.age }}
        apiKey: ${{ secrets.API_KEY }}
        apiKeySecret: ${{ secrets.API_KEY_SECRET }}
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        accessTokenSecret: ${{ secrets.ACCESS_TOKEN_SECRET }}
