name: Tweet current age criteria

on:
  push:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install gems
      run: |
        bundle install --jobs 4 --retry 3
    - name: Get current age criteria
      id: criteria
      run: echo ::set-output name=age::$(bundle exec ruby script/get_current_age_criteria.rb)
    - name: Tweet current age criteria
      uses: devigned/go-twitter-action@v1
      with:
        message: ${{ steps.criteria.outputs.age }}
        apiKey: ${{ secrets.API_KEY }}
        apiKeySecret: ${{ secrets.API_KEY_SECRET }}
        accessToken: ${{ secrets.ACCESS_TOKEN }}
        accessTokenSecret: ${{ secrets.ACCESS_TOKEN_SECRET }}
